## Tensorflow Basics

- TF Basic Syntax
- TF Graphs
- TF Variables
- TF Placeholders

### Code

- Tensorflow Neural Network
- Tensorflow Regression
- Tensorflow Classification

### 1. TF Basic Syntax

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.15.0


In [3]:
hello = tf.constant("Hello ")
world = tf.constant("World")

In [4]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [5]:
with tf.Session() as sess:
    # tensorflow operations to be run
    result = sess.run(hello+world)

In [6]:
result

b'Hello World'

In [7]:
## Addition

a = tf.constant(10)
b = tf.constant(20)

In [8]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [9]:
result

30

In [10]:
### Operations
const = tf.constant(10)
fill_mat = tf.fill((4,4), 10)
myzeros = tf.zeros((4,4))
myones = tf.ones((4,4))
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [11]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [12]:
## Interactive sessions (jupyter)
sess = tf.InteractiveSession()
tf.InteractiveSession().close()

c:\windows\system32\dl_13\lib\site-packages\tensorflow_core\python\client\session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [13]:
for op in my_ops:
    #print(sess.run(op))
    # evaluation
    print(op.eval())
    print()

10

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[-0.15380357 -2.8882596  -0.53837067 -0.5037145 ]
 [ 0.2389663   1.4620384   0.89291054  0.18896706]
 [ 1.8613199  -0.19151457 -1.1271305   0.42155576]
 [-0.6328804  -0.7736265   0.7195593  -0.9444039 ]]

[[0.85337794 0.0844413  0.9668336  0.12176228]
 [0.04086006 0.08460975 0.02557588 0.29830444]
 [0.06605554 0.85537624 0.7532815  0.02339232]
 [0.9527024  0.17858696 0.21710193 0.25184786]]



In [14]:
a = tf.constant([[1,2], [3,4]])

In [15]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [16]:
b = tf.constant([[10], [100]])

In [17]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [18]:
result = tf.matmul(a,b)

In [19]:
sess.run(result)

array([[210],
       [430]])

In [20]:
result.eval()

array([[210],
       [430]])

## 2. TF Graphs

- Start of TF --> Default graph is created

In [21]:
import tensorflow as tf

In [22]:
n1 = tf.constant(1)
n2 = tf.constant(2)

n3 = n1+n2

with tf.Session() as sess:
    result = sess.run(n3)
result

3

In [23]:
print(tf.get_default_graph())

In [24]:
g = tf.Graph()

In [25]:
graph_one = tf.get_default_graph()

In [26]:
graph_two = tf.Graph()

In [27]:
with graph_two.as_default():
    print(graph_two is tf.get_default_graph())

True


## 3. TF Variables and Placeholders

- Optimization process --> TF tunes the parameters of the model
- Variables can hold the values of weights abd biases throughout the session
- Variables need to be initialized
- Placeholders are initially empty and are used to feed in the actual training examples --> They do need a declared expected data type with an optional `shape` argument

In [28]:
import tensorflow as tf

In [29]:
sess = tf.InteractiveSession()

In [30]:
my_tensor = tf.random_uniform((4,4), 0,1)

In [31]:
my_var = tf.Variable(initial_value=my_tensor)

In [33]:
init = tf.global_variables_initializer()

In [34]:
sess.run(init)

In [35]:
sess.run(my_var)

array([[0.8059163 , 0.69362307, 0.6857747 , 0.4251318 ],
       [0.13415313, 0.41583705, 0.28419256, 0.99995255],
       [0.6868423 , 0.66414547, 0.7871698 , 0.02093673],
       [0.91479576, 0.3157444 , 0.55137455, 0.91454375]], dtype=float32)

In [37]:
ph = tf.placeholder(tf.float32, shape=(None,4))

In [38]:
tf.InteractiveSession().close()

c:\windows\system32\dl_13\lib\site-packages\tensorflow_core\python\client\session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '
